### ISSUE TITLE
Please tell me different option for Teensy 3.2

### ISSUE THREAD

**Issue by sumansaurabh699** [daniel5458h/barrett950#1]
Can i use Arduino Nano or Raspberry Pi Pico

**Comment by daniel5458h** [comment]
Hi,

The Raspberry Pi Pico is 3.3V, while the radio uses the 5V standard, you need a way to adapt the levels. The Arduino Nano can handle 5V, but its processing power and memory is too low for all the functions to run. Maybe you can remove some functions.

The Teensy 3.2 is about $20, I don't think the price difference is worth the extra effort, but that's up to you.

Best regards,
Daniel.

**Comment by sumansaurabh699** [comment]
Thanks Sir for reply
Teensy 3.2 is little bit costly for me ( $27 in India )
I will try Arduino Nano
If there is any further problem, hope you will help.

Best regards,
Suman Saurabh
 VU3ZHD
From India

**Comment by daniel5458h** [comment]
Good luck!
